projects:
  amplifyDatasource:
    schemaPath: src/graphql/schema.json
    includes:
      - employeePut
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
